import { ImageResponse } from "next/og";
import { identity } from "@/content/identity";
// Generated by scripts/generate-writing-meta.mjs in prebuild — the edge runtime
// cannot read content/writing/*.mdx from the filesystem, so OG metadata comes
// from this build-time JSON that can never drift from the MDX sources.
import writingOgPosts from "@/content/writing-meta.json";

export const runtime = "edge";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

type WritingOgImageProps = {
  params: {
    slug: string;
  };
};

function truncate(value: string, maxLength = 120): string {
  return value.length > maxLength ? `${value.slice(0, maxLength - 1).trim()}…` : value;
}

export function generateStaticParams() {
  return writingOgPosts.map((post) => ({ slug: post.slug }));
}

export default function WritingOpenGraphImage({ params }: WritingOgImageProps) {
  const post = writingOgPosts.find((entry) => entry.slug === params.slug) ?? {
    slug: params.slug,
    title: params.slug,
    description: "",
  };

  return new ImageResponse(
    (
      <div
        style={{
          height: "100%",
          width: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#000000",
          color: "#E8E4DE",
          padding: "72px 80px",
          fontFamily: "system-ui, sans-serif",
        }}
      >
        <div style={{ display: "flex", color: "#8A8578", fontSize: 22 }}>{identity.lockup}</div>
        <div style={{ display: "flex", flexDirection: "column", gap: 28 }}>
          <div style={{ width: "100%", height: 2, background: "#C4B5A0" }} />
          <div style={{ display: "flex", fontSize: 64, fontWeight: 700, lineHeight: 1.05 }}>
            {post.title}
          </div>
          <div style={{ display: "flex", maxWidth: 980, fontSize: 30, lineHeight: 1.35, color: "#8A8578" }}>
            {truncate(post.description)}
          </div>
        </div>
      </div>
    ),
    { ...size },
  );
}
